### ISSUE TITLE
Please provide a better Table of Contents

### ISSUE THREAD

**Issue by formorer** [Icinga/icinga-docs-tools#3]
With the new docs layout it is not possible to see the full content of a software component, clicking on a subtopic, just reveals the toc of that subtopic on the right side. Proposal: a click on a specific project (i.e. icinga2) should display the full TOC of that component (TOC over all subtopics).

**Comment by bobapple** [comment]
The main navigation is now open by default for every project. Clicking on a subject will open its TOC on the right side. There will be no view where everything is open by default (like on the previous version on docs.icinga.com)
