### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-docs-tools#4]
It would be really helpful to add a 404 handling page.

This page should show a nice error, and lead the user back to the overview / TOC.

Currently the only thing happens is:

https://www.icinga.com/docs/icinga2/latest/doc/10-old-doc
`Not found - The requested URL /docs/icinga2/latest/doc/10-old-doc was not found on this server.`

**Comment by bobapple** [comment]
As discussed offline, I added some configuration to display at least the default 404 page of icinga.com. Showing a "sane" 404 page (including TOC) requires some more changes that we may do "some other time"

Thanks for reporting
